pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                script{
                    def image = docker.build("todo-app:${env.BUILD_ID}", "./docker/Dockerfile")
                }
            }
        }
    }
    post{
        success{
            archiveArtifacts artifacts: 'todo-app', fingerprint: true
        }
    }
}