pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                script{
                    def image = docker.build("todo-app:${env.BUILD_ID}", "-f docker/Dockerfile .")
                }
            }
        }
    }
    environment{
        TELEGRAM_TOKEN_ID = credentials('telegram_token_id')
        TELEGRAM_CHAT_ID = credentials('telegram_chat_id')
        API_URL = "https://api.telegram.org/bot${TELEGRAM_TOKEN_ID}/sendMessage"
        MESSAGE = "${BUILD_TAG}:${currentBuild.currentResult}"
    }
    post{
        always{
            sh '''curl -s -X POST $API_URL -d chat_id=$TELEGRAM_CHAT_ID -d text="$MESSAGE"'''
        }
    }
}