pipeline{
    agent any
    environment{
        TELEGRAM_TOKEN_ID = credentials('telegram_token_id')
        TELEGRAM_CHAT_ID = credentials('telegram_chat_id')
        API_URL = "https://api.telegram.org/bot${TELEGRAM_TOKEN_ID}/sendMessage"
        APP_IMAGE_NAME = "todo-app:${env.BUILD_ID}"
        MESSAGE = "${BUILD_TAG}:${currentBuild.currentResult}.\nDocker image: ${APP_IMAGE_NAME}"
        DOCKERFILE_PATH = "docker/Dockerfile"
    }
    stages{
        stage('Build'){
            steps{
                sh '''curl -s -X POST $API_URL -d chat_id=$TELEGRAM_CHAT_ID -d text="Build started $BUILD_URL"'''
                sh "docker build -f ${DOCKERFILE_PATH} -t ${APP_IMAGE_NAME} ."
            }
        }
        stage('Deploy'){
            steps{
                sh '''curl -s -X POST $API_URL -d chat_id=$TELEGRAM_CHAT_ID -d text="Running docker image..."'''
                sh "docker run -d -p 49002:8000 ${APP_IMAGE_NAME}"
            }
        }
    }
    post{
        always{
            sh '''curl -s -X POST $API_URL -d chat_id=$TELEGRAM_CHAT_ID -d text="$MESSAGE"'''
        }
    }
}